### ISSUE TITLE
Custom Key Binding

### ISSUE THREAD

**Issue by avamsi** [ssundarraj/commander#2]
Provide the option for custom key-binding may be?
Can I use `ctrl - shift - p` for this? It seems to be set for print command.

**Comment by ssundarraj** [comment]
You can set this manually in Chrome by going to [chrome://extensions](chrome://extensions) and clicking the "Keyboard Shortcuts" link ~~at the bottom of the page~~ in the menu on the left.

**Comment by avamsi** [comment]
Didn't know that. Thank you!

**Comment by ValentinCreative** [comment]
@ssundarraj hum it seems this link disappeared (Chrome 69+)

**Comment by ssundarraj** [comment]
@ValentinCreative Can you check the hamburger menu on the left?

**Comment by ValentinCreative** [comment]
@ssundarraj Indeed it's here, thanks. 👍 
… hamburger menus … 😩
